###############################################################
# Program:
#     Checkpoint 04b, Classes
#     Brother Alvey, CS165
# Author:
#     Gabriel Ikpaetuk
# Summary:
#     This program has a class for a date, that holds 
#     a month, day, and year, and can display it in American 
#     format (mm/dd/yyyy), European format (dd/mm/yyyy), and 
#     the ISO 8601 standard format (yyyy-mm-dd).
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : date.h date.cpp check04b.cpp
	g++ date.cpp check04b.cpp
