###############################################################
# Program:
#     Checkpoint 11b, Class Templates
#     Brother Alvey, CS165
# Author:
#     Gabriel Ikpaetuk
# Summary:
#     Summaries are not necessary for checkpoint assignments.
###############################################################


a.out : check11b.cpp pair.h
	g++ check11b.cpp

