###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Alvey, CS165
# Author:
#     Gabriel Ikpaetuk
# Summary:
#     This program creates a library to handle products: to  
#     store their information, compute shipping costs, and 
#     display receipts.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

