###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Alvey, CS165
# Author:
#     Gabriel Ikpaetuk
# Summary:
#     This program creates a library to handle products: to  
#     store their information, compute shipping costs, and 
#     display receipts. It also manages customers' orders
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

